name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths:
      - "apps/landing/**"
      - "apps/widget/**"
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  S3_BUCKET: aura-vote-landing
  DIST_DIR: out

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build widget
        working-directory: apps/widget
        run: pnpm build

      - name: Build landing page
        working-directory: apps/landing
        run: pnpm build

      - name: Copy widget output to landing out directory
        run: |
          mkdir -p apps/landing/${{ env.DIST_DIR }}/widget
          cp apps/widget/dist/widget.iife.js apps/landing/${{ env.DIST_DIR }}/widget/widget.iife.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync apps/landing/${{ env.DIST_DIR }} s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2TDBQKPMCOKLW \
            --paths "/*"
